safe: false
source: .
destination: ./_site
plugins_dir: ./_plugins
highlighter: rouge
markdown: kramdown
exclude: ['_DOCS', '_SCRIPTS', '.travis.yml', '.travis.d', '.sass-cache', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'LICENSE.md']

plugins:
  - jekyll-assets

url: http://ndn-retreat.url.com
baseurl: 

# Configuration for site
title: NDN Retreat

# google_analytics_id: UA-83529610-1

# Configuration for navbar.html
menu:
- name: Home
  url: /
- name: Accommodations
  icon: fa-map
  url: /accommodations.html

colors:
  highlight: 2E85C2
  highlight-darker: 2E85C2
  hfont: F9E90C

  program:
    break-background: d1d1d1

assets:
  caching:
    path: .sass-cache/assets
  features:
    automatic_img_size: false

  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/bower
    - _assets/calls

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
